server:
  port: 8086

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: debitcarddb
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jackson:
    default-property-inclusion: NON_NULL

service:
  client:
    uri: http://localhost:8081/api/v1/client
  account:
    uri: http://localhost:8082/api/v1/account
